
// Copyright (c) 2015-2020 niXman (i dot nixman dog gmail dot com). All
// rights reserved.
//
// This file is part of FQUEUE(https://github.com/niXman/fqueue) project.
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
//
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include <fqueue/fqueue.hpp>

#include <iostream>

/***************************************************************************/

void usage(const char *argv0) {
    const char *p = std::strrchr(argv0, '/');
    p = (p ? p+1 : "info");

    std::cout << "usage: " << p << " <fqueue file name> <path to records dir>" << std::endl;
}

/***************************************************************************/

int main(int argc, char **argv) {
    if ( argc != 3 ) {
        usage(argv[0]);
        return EXIT_SUCCESS;
    }

    const char *fname = argv[1];
    if ( 0 != ::access(fname, F_OK) ) {
        std::cerr << "fqueue file \"" << fname << "\" is not exists. terminate." << std::endl;
        return EXIT_FAILURE;
    }

    const char *path = argv[2];
    if ( 0 != ::access(path, F_OK) ) {
        std::cerr << "records dir \"" << path << "\" is not exists. terminate." << std::endl;
        return EXIT_FAILURE;
    }

    fqueue::fqueue fq(fname);
    if ( fq.empty() ) {
        std::cerr << "fqueue file \"" << fname << "\" is empty. terminate." << std::endl;
        return EXIT_SUCCESS;
    }
}

/***************************************************************************/
